services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/canadahackers/local_settings.py:/app/canadahackers/local_settings.py:ro
      - db_data:/app/data
      - /srv/static:/app/static2


volumes:
  db_data:
  static_volume:
